sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react .

script:
  - echo "Skipping tests"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "ap-south-1"
  app: "react-docker"
  env: "React-docker-env"
  bucket_name: "the-target-S3-bucket"
