version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  test:
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  command: ["npm", "run", "test"]